name: google_docs_clone
description: "Creating a Google Docs Clone for both the Web and the Android"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  shared_preferences: ^2.3.5
  routemaster: ^1.0.1
  logger: ^2.5.0
  flutter_quill: ^10.8.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/