version: "3.8"

services:

  app: 
    build: .
    container_name: google-docs-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    # environment:
      # - name=value
    networks:
      - mynetwork

    
  mongo:
      image: mongo:6.0
      container_name: mongodb
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge
